## 哈夫曼树

In [26]:
"""
方法1：
题目1：哈夫曼树建立
题目描述：给定 n = 8个节点，其对应权值 W = [7,19,2,6,32,3,21,10],对这 8 个节点构建哈夫曼树
解题思路：
（1）确定存储方式：数组存储，需要 1 个数组
    1）存储哈夫曼树的数组：ha ：shape为 (n + (n-1) + 1)*4,即 2n 行，4列
    注意：哈夫曼树会多生成 n-1 个节点，原则上使用 n+n-1 = 2n-1 行即可，但多加 1 行，因为不想使用第0行，
    这给定的 n 个节点，从数组第 1 行开始存储即可，不使用第 0 行，方便进行后续操作。
    这 4 列为：weight（权值）、parent（父节点序号）、left（左节点序号）、right（右节点序号）
（2）生成树的方法：
    1）口诀：1.构造森林全是根，2.选用两小造新树，3.删除两小添新人，4.重复 2、3 剩单根
    2）初始化该数组，生成 2n*4 的二维数组，初始值全为 0
    3）将给定的 n 个节点，从第 1 行开始，一次存入对应权值
    4）按照口诀依次生成新节点，并填入节点对应的 parent、left、right 节点序号
"""
# coding:utf-8

class Solution:
    def hafu(self, data):
        # 初始化数组生成：2n*4 的二维数组
        ha = []
        for i in range(2 * len(data)):
            ha_mid = []
            for j in range(4):
                ha_mid.append(0)
            ha.append(ha_mid)
        # 依次将这 n 个节点存入数组
        for i in range(1, len(data) + 1):
            ha[i][0] = data[i - 1]
        # 将 data 重新生成
        new_data = {}
        for i in range(len(data)):
            new_data[i + 1] = data[i]

        # 进行while循环
        while len(new_data) > 1:
            # 将 new_data 按照key排序
            """
            注意：此处如果仅：
            sorted(new_data.items(), key=lambda item: item[1])
            而不用：
            new_data1 = {}
            for key,value in items:
                new_data1[key] = value
            new_data = new_data1
            会导致错误，因为此时new_data自身并没有改变
            """
            items = sorted(new_data.items(), key=lambda item: item[1])
            new_data1 = {}
            for key,value in items:
                new_data1[key] = value
            new_data = new_data1
            # 选择 3 个指针分别指向 2个最小的数的位置，新生成树的位置
            # 选择最小的两个数的位置
            num1, num2 = list(new_data.keys())[0], list(new_data.keys())[1]
            # 生成新节点
            num_new = ha[num1][0] + ha[num2][0]
            # 新节点位置
            num_new_loc = max(new_data.keys()) + 1
            # 新节点接着空位置往下存
            ha[num_new_loc][0] = num_new
            # 左节点
            ha[num_new_loc][2] = num1
            # 右节点
            ha[num_new_loc][3] = num2
            # 原来节点的父节点存入生成新节点序号
            ha[num1][1] = num_new_loc
            ha[num2][1] = num_new_loc

            # 去掉两个最小值
            new_data.pop(num1)
            new_data.pop(num2)
            # 添加新添加的值
            new_data[num_new_loc] = num_new

        return ha

if __name__ == '__main__':
    import numpy as np

    s = Solution()
    data = [7, 19, 2, 6, 32, 3, 21, 10]
    result = np.array(s.hafu(data))
    print(result)

[[  0   0   0   0]
 [  7  11   0   0]
 [ 19  13   0   0]
 [  2   9   0   0]
 [  6  10   0   0]
 [ 32  14   0   0]
 [  3   9   0   0]
 [ 21  13   0   0]
 [ 10  11   0   0]
 [  5  10   3   6]
 [ 11  12   9   4]
 [ 17  12   1   8]
 [ 28  14  10  11]
 [ 40  15   2   7]
 [ 60  15  12   5]
 [100   0  13  14]]


In [39]:
"""
方法2：使用节点形式存储
"""
class Node:
    def __init__(self,val):
        self.val = val
        self.left = None
        self.right = None

class Ha:
    def ha(self,data):
        while len(data) > 1:
            # 将data进行排序
            data = sorted(data)
            # 选取前两个数，以及两数和
            num1 = Node(data[0])
            num2 = Node(data[1])
            num  = Node(data[0]+data[1])
            # 生成一个子树
            num.left = num1
            num.right = num2
            # 删除前两个节点，添加新节点
            data.append(data[0]+data[1])
            data.pop(0)
            data.pop(0)
        return num

In [40]:
data = [1,2,3]
h = Ha()
result = h.ha(data)

In [42]:
result.val

6